#!/usr/bin/python

import os
import sys
import yaml

SCHEMA_DIRECTORY = "schemas"


def usage():
    print "Prints an example yaml data file from a schema (i.e. in "
    print SCHEMA_DIRECTORY + "/) to stdout.  Can be > redirected to a file."
    print ""
    print "Usage:"
    print "    " + " ".join([sys.argv[0],
                             "<schema_filename>",
                             "[--no-comments]",
                             "[--as-template]"])
    print ""
    print "    no-comments: Generates without title/description comments"
    print "    as-template: Generates as a jinja2 template"


class ExampleFileGenerator(object):
    def __init__(self, no_comments=False, as_template=False):
        self.has_comments = not no_comments
        self.as_template = as_template

    def generate_example_from_schema(self, schema_filename):
        self.example_lines = []
        with open(schema_filename, 'r') as file:
            schema = yaml.safe_load(file.read())

        if self.has_comments:
            self.add_example_header(schema)

        self.add_example_content(schema)

        return "\n".join(self.example_lines)

    def add_example_header(self, schema):
        self.example_lines.append("#" * 79)
        if "title" in schema:
            self.example_lines.append("# " + schema["title"])
        if "description" in schema:
            self.example_lines.append("#")
            self.example_lines.append("# " + schema["description"])
        if self.as_template:
            self.example_lines.append("#")
            self.example_lines.append(
                '# Automatically generated by {{ generator_script'
                ' | default("script") }}.')
        self.example_lines.append("#")
        self.example_lines.append("")

    def add_example_content(self, schema):
        is_list = schema["type"] == "array"

        if is_list:
            if "items" in schema and "title" in schema["items"]:
                item_name = schema["items"]["title"]
                list_name = schema["items"]["title"].lower() + "s"
            else:
                item_name = schema["title"][0:-1]
                list_name = schema["title"].lower()
            if self.as_template:
                self.example_lines.append(
                    "{%% if %s is defined and %s %%}" % (list_name,
                                                         list_name))
                self.example_lines.append("{%% for item in %s %%}" % list_name)

            if self.has_comments and "title" in schema:
                item_index = "1"
                if self.as_template:
                    item_index = "{{ loop.index }}"
                self.example_lines.append("#")
                self.example_lines.append("# %s %s" % (item_name,
                                                       item_index))
                self.example_lines.append("#")
            self.example_lines.append("-")
            self.add_example_fields(schema["items"]["properties"], is_list)

            if self.as_template:
                self.example_lines.append("{% endfor %}")
                self.example_lines.append("{% else %}")
                self.example_lines.append("[ ]")
                self.example_lines.append("{% endif %}")

        else:
            self.add_example_fields(schema["properties"])

    def add_example_fields(self, field_dict, is_list=False):
        for name, field in sorted(field_dict.iteritems(),
                                  key=lambda (k, v): (v["propertyOrder"], k)):
            self.add_example_field(name, field, is_list)

    def add_example_field(self, name, field, is_list=False):
        indent = ""

        if is_list:
            indent = "    "

        if self.has_comments:
            if "title" in field:
                self.example_lines.append("%s# < %s >" % (indent,
                                                          field["title"]))

            if "description" in field:
                self.example_lines.append(
                    "%s# %s" % (indent, field["description"]))

            if "enum" in field:
                self.example_lines.append(
                    "%s# (%s) " % (indent, ", ".join(field["enum"])))

            self.example_lines.append("%s#" % indent)

        if "default" in field:
            if self.as_template:
                item_name = ""
                if is_list:
                    item_name = "item."

                self.example_lines.append(
                    "%s{%%- if %s%s is defined %%}" % (indent,
                                                       item_name,
                                                       name))

                value = self.get_example_value(name, field, is_list)
                self.example_lines.append("%s%s: %s" % (indent, name, value))
                if self.has_comments:
                    self.example_lines.append("%s{%%- else %%}" % indent)

            if self.has_comments:
                self.example_lines.append("%s# %s: %s" % (indent,
                                                          name,
                                                          field["default"]))

            if self.as_template:
                self.example_lines.append("%s{%%- endif %%}" % indent)

        else:
            value = self.get_example_value(name, field, is_list)
            self.example_lines.append("%s%s: %s" % (indent, name, value))

        if self.has_comments:
            self.example_lines.append("")

    def get_example_value(self, name, field, is_list):
        field_type = "string"
        if "type" in field:
            field_type = field["type"]
        if self.as_template:
            return self.get_example_template_value(name, field_type,
                                                   is_list)
        else:
            return self.get_example_placeholder_value(field_type)

    def get_example_template_value(self, name, field_type, is_list):
        item_name = ""
        if is_list:
            item_name = "item."
        if field_type == "integer":
            return "{{ %s%s }}" % (item_name, name)
        elif field_type == "boolean":
            return "{{ %s%s | lower }}" % (item_name, name)
        elif field_type == "array":
            return ('[ {%% for i in %s%s | default([]) %%}"{{ i }}", '
                    '{%% endfor %%}]' % (item_name, name))
        else:
            return '"{{ %s%s }}"' % (item_name, name)

    def get_example_placeholder_value(self, field_type):
        if field_type == "integer":
            return "0"
        elif field_type == "boolean":
            return "false"
        elif field_type == "ipv4":
            return "0.0.0.0"
        elif field_type == "array":
            return "[ ]"
        else:
            return '""'


def main():
    if len(sys.argv) < 2 or "-h" in sys.argv or "--help" in sys.argv:
        usage()
        exit(1)

    schema_filename = sys.argv[1]

    no_comments = "--no-comments" in sys.argv
    as_template = "--as-template" in sys.argv

    generator = ExampleFileGenerator(no_comments, as_template)

    if schema_filename.find(".") == -1:
        schema_filename = schema_filename + ".json"

    if os.path.isfile(schema_filename):
        print generator.generate_example_from_schema(schema_filename)
    else:
        schema_filename = os.path.join(SCHEMA_DIRECTORY, schema_filename)
        if os.path.isfile(schema_filename):
            print generator.generate_example_from_schema(schema_filename)
        else:
            raise Exception("Could not find schema file %s" % schema_filename)


if __name__ == '__main__':
    main()
