#!/usr/bin/env bash
set -e

#################################################################################
#                                Install COMMANDS                               #
#################################################################################
MENU+=(',install'                      'Install all components'                      'playbook'    'install_everything'                   '')
MENU+=(',install,vsds'                 'Install VSDs'                                'playbook'    'install_vsd'                          ',install')
MENU+=(',install,vsds,predeploy'       'Pre-deploy VSDs'                             'playbook'    'vsd_predeploy'                        ',install,vsds')
MENU+=(',install,vsds,deploy'          'Deploy VSDs deploy'                          'playbook'    'vsd_deploy'                           ',install,vsds')
MENU+=(',install,vsds,postdeploy'      'Post-deploy VSDs '                           'playbook'    'vsd_postdeploy'                       ',install,vsds')
MENU+=(',install,vscs'                 'Install VSCs'                                'playbook'    'install_vscs'                         ',install')
MENU+=(',install,vscs,predeploy'       'Pre-deploy VSCs'                             'playbook'    'vsc_predeploy'                        ',install,vscs')
MENU+=(',install,vscs,deploy'          'Deploy VSCs deploy'                          'playbook'    'vsc_deploy'                           ',install,vscs')
MENU+=(',install,vscs,postdeploy'      'Post-deploy VSCs '                           'playbook'    'vsc_postdeploy'                       ',install,vscs')
MENU+=(',install,vstats'               'Install VSTATs'                              'playbook'    'install_vstats'                       ',install')
MENU+=(',install,vstats,predeploy'     'Pre-deploy VSTATs'                           'playbook'    'vstat_predeploy'                      ',install,vstats')
MENU+=(',install,vstats,deploy'        'Deploy VSTATs deploy'                        'playbook'    'vstat_deploy'                         ',install,vstats')
MENU+=(',install,vstats,postdeploy'    'Post-deploy VSTATs '                         'playbook'    'vstat_postdeploy'                     ',install,vstats')

#################################################################################
#                              Upgrade COMMANDS                                 #
#################################################################################

MENU+=(',upgrade'                      'Upgrade all components'                      'playbook'    'upgrade_everything'                   '')
MENU+=(',upgrade,vsds'                 'Upgrade VSDs'                                'playbook'    'vsds_upgrade'                         ',upgrade')
MENU+=(',upgrade,vscs'                 'Upgrade VSCs'                                'playbook'    'vscs_upgrade'                         ',upgrade')
MENU+=(',upgrade,vstats'               'Upgrade VSTATs'                              'playbook'    'vstats_upgrade'                       ',upgrade')

#################################################################################
#                               Health COMMANDS                                 #
#################################################################################
MENU+=(',health'                      'Health check for all components'              'playbook'    'upgrade_everything'                   '')
MENU+=(',health,vsds'                 'Health check for VSDs'                        'playbook'    'vsds_upgrade'                         ',health')
MENU+=(',health,vscs'                 'Health check for VSCs'                        'playbook'    'vscs_upgrade'                         ',health')
MENU+=(',health,vstats'               'Health check for VSTATs'                      'playbook'    'vstats_upgrade'                       ',health')

#################################################################################
#                                Tools COMMANDS                                 #
#################################################################################
MENU+=(',tools'                       'Tools'                                        'tools'       ''                                     '')
MENU+=(',tools,unzip,images'          'Unzip Nuage packed images'                    'tools'       'unzip-files'                          '.tools')
MENU+=(',tools,convert,buildvars'     'Convert legacy build_vars.yml to deployment'  'tools'       'convert-build-vars-to-deployments'    ',tools')            
MENU+=(',tools,generate,example'      'Generate example deployment from schema'      'tools'       'generate-example-from-schema'         ',tools')      
MENU+=(',tools,encrypt,credentials'   'Encrypt credentials'                          'tools'       'encrypt-credentials'                  ',tools')

