#!/usr/bin/env bash
set -ex
#
# Wrapper around ansible-playbook for the installation of Nuage components

PLAYBOOK=$@

if [[ ! -a $PLAYBOOK  ]]; then
  PLAYBOOK="./playbooks/$PLAYBOOK"
  if [[ ! -a $PLAYBOOK  ]]; then
    echo "Requested Metro-Playbook could not be found"
    exit 1
  fi
fi

echo "Executing $PLAYBOOK"

$(which ansible-playbook) -i hosts $PLAYBOOK
