#!/bin/sh

# WARNING: Any paths defined in the deployment files must be relative to this folder. No absolute paths, and no paths outside of this folder

#TODO: we need to pass in the proxy env variables to be able to use pip and yum on a corp network
TAG=$(git rev-parse --short HEAD)
docker image inspect metroaecontaine1r:$TAG > /dev/null 2>&1
if [[ "$?" != "0" ]]
then
    echo "The docker image for this repo head does not exist. We will build it. Press any key to continue"
    read -n 1
    set -e
    docker build -t metroaecontainer:$TAG .
    set +e
fi

# Run the command inside docker
docker run --rm -ti -v `pwd`:/metroae metroaecontainer:$TAG ./metroae $@
