#!/bin/bash
set -e

log_status () {
        status-set maintenance $1
        juju-log $1
}

install_packages () {
        log_status "Installing required packages"
        apt-get install -y git wget
}

get_images () {
        log_status "Pulling the image archive"
        mkdir -p images/vsc/single_disk
        cd images/vsc/single_disk
        wget http://135.227.146.142/packages/vsp/5.3.3/vsc.tar.gz
}

unpack_images () {
        log_status "Unpacking the image archive"
        /bin/gunzip vsc.tar.gz
        /bin/tar -xf vsc.tar
        mv vsc.qcow2 vsc_singledisk.qcow2
}

clone_metroae () {
        log_status "Cloning MetroÆ"
        git clone https://casodevops:casoCASO1\$\@github.com/nuagenetworks/nuage-metro.git
        cd nuage-metro
        git checkout u1804
}

run_metroae_setup () {
        log_status "Running metro-setup"
        ./metro-setup.sh
}

install_packages

get_images

unpack_images

clone_metroae

run_metroae_setup

ansible --version
