#!/bin/bash
set -e 
status-set maintenance "Setting up the MetroÆ Environment"
apt-get install -y git wget
mkdir -p images/vsc/single_disk
cd images/vsc/single_disk
wget http://135.227.146.142/packages/vsp/5.3.3/vsc.tar.gz
/bin/gunzip vsc.tar.gz
/bin/tar -xf vsc.tar
mv vsc.qcow2 vsc_singledisk.qcow2
git clone https://casodevops:casoCASO1\$\@github.com/nuagenetworks/nuage-metro.git
cd nuage-metro
git checkout u1804
./metro-setup.sh
ansible --version
