#!/bin/bash
# VM Automation of New Instance Bridge Configuration
# Only to be used with VMs on OpenStack Jen project
# This script configures br-eth1 for Jen backend net

IP2use="$1"
removed=${IP2use:9}
mgmtIP=${IP2use:0:9}
incremented=$(($removed+110))
mgmtIP="${mgmtIP}$incremented"
gwIP="${mgmtIP}1"
dns1=128.251.10.25
dns2=128.251.10.29

echo "--> Configuring Device Interface for Bridge"

FILE="/etc/sysconfig/network-scripts/ifcfg-eth1"

/bin/cat <<EOM >$FILE
# Generated by Bridge Config Automation Script
DEVICE="eth1"
NAME="eth1"
TYPE=Ethernet
BRIDGE="br-eth1"
PEERROUTES=no
PEERDNS=no
IPV6INIT=no
MTU=9000
EOM

echo "--> Configuring Bridge with given IP"

FILE="/etc/sysconfig/network-scripts/ifcfg-br-eth1"

/bin/cat <<EOM >$FILE
DEVICE="br-eth1"
NAME="br-eth1"
TYPE=Bridge
BOOTPROTO=static
ONBOOT=yes
DELAY=0
DEFROUTE=no
PEERROUTES=no
IPV6INIT=no
MTU=9000
IPADDR=$IP2use
PREFIX=24
GATEWAY=$gwIP
DNS1=$dns1
DNS2=$dns2
EOM

echo "--> Restarting network with new configurations"

systemctl restart network

echo "--> Creating ssh key pair"

echo "y \n" | ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa

echo "--> Installing sshpass"

yum -y install sshpass

echo "--> Copying ssh keys to localhost"

sshpass -p "caso" ssh-copy-id localhost

echo "--> Enabling dnsmasq"

systemctl restart dnsmasq

systemctl enable dnsmasq

echo "--> Setting hosts for default jenkins.example.com IPs"
echo "--> with the correct naming convention"

echo $mgmtIP "   jenkinsvsd1.example.com" >> /etc/hosts

if [ $2 = "ha" ];
then
    echo "--> This is a HA deployment"

    echo $mgmtIP "   xmpp.example.com" >> /etc/hosts
    
    mgmtIP=${mgmtIP:0:9}
    incremented=$(($incremented+10))
    mgmtIP="${mgmtIP}$incremented"

    echo $mgmtIP "   jenkinsvsd2.example.com" >> /etc/hosts
    echo $mgmtIP "   xmpp.example.com" >> /etc/hosts

    mgmtIP=${mgmtIP:0:9}
    incremented=$(($incremented+10))
    mgmtIP="${mgmtIP}$incremented"

    echo $mgmtIP "   jenkinsvsd3.example.com" >> /etc/hosts
    echo $mgmtIP "   xmpp.example.com" >> /etc/hosts
fi

mgmtIP=${mgmtIP:0:9}
incremented=$(($incremented+10))
mgmtIP="${mgmtIP}$incremented"

echo $mgmtIP "   jenkinsvsc1.example.com" >> /etc/hosts

mgmtIP=${mgmtIP:0:9}
incremented=$(($incremented+10))
mgmtIP="${mgmtIP}$incremented"

echo $mgmtIP "   jenkinsvsc2.example.com" >> /etc/hosts

mgmtIP=${mgmtIP:0:9}
incremented=$(($incremented+10))
mgmtIP="${mgmtIP}$incremented"

echo $mgmtIP "   jenkinsvstat1.example.com" >> /etc/hosts

if [ $2 = "ha" ];
then
    mgmtIP=${mgmtIP:0:9}
    incremented=$(($incremented+10))
    mgmtIP="${mgmtIP}$incremented"

    echo $mgmtIP "   jenkinsvstat2.example.com" >> /etc/hosts

    mgmtIP=${mgmtIP:0:9}
    incremented=$(($incremented+10))
    mgmtIP="${mgmtIP}$incremented"

    echo $mgmtIP "   jenkinsvstat3.example.com" >> /etc/hosts
fi

mgmtIP=${mgmtIP:0:9}
incremented=$(($incremented+10))
mgmtIP="${mgmtIP}$incremented"

echo $mgmtIP "   jenkinsvnsutil1.example.com" >> /etc/hosts

mgmtIP=${mgmtIP:0:9}
incremented=$(($incremented+10))
mgmtIP="${mgmtIP}$incremented"

echo $mgmtIP "   jenkinsnsgv1.example.com" >> /etc/hosts
