#!/bin/sh

cd docker
TAG=$(git rev-parse --short HEAD)
if [[ -n "$HTTP_PROXY" ]]
then
    export buildproxy="--build-arg http_proxy=$HTTP_PROXY"
fi
if [[ -n "$http_proxy" ]]
then
    export buildproxy="--build-arg http_proxy=$http_proxy"
fi
if [[ -n "$HTTPS_PROXY" ]]
then
    export buildproxy="$buildproxy --build-arg https_proxy=$HTTPS_PROXY"
fi
if [[ -n "$https_proxy" ]]
then
    export buildproxy="$buildproxy --build-arg https_proxy=$https_proxy"
fi

cp -f ../yum_requirements.txt ./
cp -f ../pip_requirements.txt ./
cp -f ../openstack_requirements.txt ./

docker --version 2>/dev/null
if [[ $? != 0 ]];
then
PLATFORM_TYPE=podman
else
PLATFORM_TYPE=docker
fi

if [[ "$PLATFORM_TYPE" == "podman" ]];
then
podman build $buildproxy -t metroaecontainer:$TAG .
else
docker build $buildproxy -t metroaecontainer:$TAG .
fi
if [[ "$PLATFORM_TYPE" == "podman" ]];
then
    if [[ "$1" != "raw" ]]
    then
        podman save -o metroae-docker-container.tar metroaecontainer:$TAG 
        echo "File metroae-docker-container.tar was created"
    fi
else
    if [[ "$1" != "raw" ]]
    then
        docker save -o metroae-docker-container.tar metroaecontainer:$TAG 
        echo "File metroae-docker-container.tar was created"
    fi
fi

