#!/usr/bin/env bash
set -e

#################################################################################
#                                Install COMMANDS                               #
#################################################################################
MENU+=(',install'                      'Run installations of Nuage components'        'playbook'    'install_everything'                   '')
MENU+=(',install,everything'           'Install all Nuage components'                 'playbook'    'install_everything'                   ',install')
MENU+=(',install,vsds'                 'Install Nuage VSDs'                           'playbook'    'install_vsd'                          ',install')
MENU+=(',install,vsds,predeploy'       'Pre-deploy Nuage VSDs'                        'playbook'    'vsd_predeploy'                        ',install,vsds')
MENU+=(',install,vsds,deploy'          'Deploy Nuage VSDs'                            'playbook'    'vsd_deploy'                           ',install,vsds')
MENU+=(',install,vsds,postdeploy'      'Post-deploy Nuage VSDs '                      'playbook'    'vsd_postdeploy'                       ',install,vsds')
MENU+=(',install,vscs'                 'Install Nuage VSCs'                           'playbook'    'install_vscs'                         ',install')
MENU+=(',install,vscs,predeploy'       'Pre-deploy Nuage VSCs'                        'playbook'    'vsc_predeploy'                        ',install,vscs')
MENU+=(',install,vscs,deploy'          'Deploy Nuage VSCs'                            'playbook'    'vsc_deploy'                           ',install,vscs')
MENU+=(',install,vscs,postdeploy'      'Post-deploy Nuage VSCs '                      'playbook'    'vsc_postdeploy'                       ',install,vscs')
MENU+=(',install,vstats'               'Install Nuage VSTATs (ES)'                    'playbook'    'install_vstats'                       ',install')
MENU+=(',install,vstats,predeploy'     'Pre-deploy Nuage VSTATs (ES)'                 'playbook'    'vstat_predeploy'                      ',install,vstats')
MENU+=(',install,vstats,deploy'        'Deploy Nuage VSTATs (ES)'                     'playbook'    'vstat_deploy'                         ',install,vstats')
MENU+=(',install,vstats,postdeploy'    'Post-deploy Nuage VSTATs (ES)'                'playbook'    'vstat_postdeploy'                     ',install,vstats')

#################################################################################
#                              Upgrade COMMANDS                                 #
#################################################################################
MENU+=(',upgrade'                      'Run upgrades of Nuage components'             'playbook'    'upgrade_everything'                   '')
MENU+=(',upgrade,everything'           'Upgrade all Nuage components'                 'playbook'    'upgrade_everything'                   ',upgrade')
MENU+=(',upgrade,vsds'                 'Upgrade Nuage VSDs'                           'playbook'    'vsds_upgrade'                         ',upgrade')
MENU+=(',upgrade,vscs'                 'Upgrade Nuage VSCs'                           'playbook'    'vscs_upgrade'                         ',upgrade')
MENU+=(',upgrade,vstats'               'Upgrade Nuage VSTATs (ES)'                    'playbook'    'vstats_upgrade'                       ',upgrade')

#################################################################################
#                               Health COMMANDS                                 #
#################################################################################
MENU+=(',health'                      'Run the health checks for Nuage components'    ''            ''                                     '')
MENU+=(',health,vsds'                 'Run heath check Nuage VSDs'                    'playbook'    'vsd_health'                           ',health')
MENU+=(',health,vscs'                 'Run heath check Nuage VSCs'                    'playbook'    'vsc_health'                           ',health')
MENU+=(',health,vstats'               'Run heath check Nuage VSTATs'                  'playbook'    'vstat_health'                         ',health')

#################################################################################
#                                Tools COMMANDS                                 #
#################################################################################
MENU+=(',tools'                       'Run MetroAE Tools'                             'tools'       ''                                     '')
MENU+=(',tools,unzip,images'          'Unzip Nuage images'                            'tools'       'unzip-files'                          ',tools')
MENU+=(',tools,generate,example'      'Generate a deployment file from its schema'    'tools'       'generate-example-from-schema'         ',tools')
MENU+=(',tools,encrypt,credentials'   'Encrypt credentials.yml in your deployment'    'tools'       'encrypt-credentials'                  ',tools')
MENU+=(',tools,convert,buildvars'     'Convert buildvars to deployment'               'tools'       'convert_build_vars_to_deployment'     ',tools')

#################################################################################
#                                Wizard                                         #
#################################################################################

MENU+=(',wizard'                      'Run MetroAE Wizard'                            'wizard'      ''                                     '')

