#!/usr/bin/env bash
set -e

#################################################################################
#                                Install COMMANDS                               #
#################################################################################
MENU+=(',install'                        'Run installations of Nuage components'              'playbook'    'install_everything'                           '')
MENU+=(',install,everything'             'Install all Nuage components'                       'playbook'    'install_everything'                           ',install')
MENU+=(',install,vsds'                   'Install Nuage VSDs'                                 'playbook'    'install_vsds'                                 ',install')
MENU+=(',install,vsds,predeploy'         'Pre-deploy install step for Nuage VSDs'             'playbook'    'vsd_predeploy'                                ',install,vsds')
MENU+=(',install,vsds,deploy'            'Deploy install step for Nuage VSDs'                 'playbook'    'vsd_deploy'                                   ',install,vsds')
MENU+=(',install,vsds,postdeploy'        'Post-deploy install step for Nuage VSDs'            'playbook'    'vsd_postdeploy'                               ',install,vsds')
MENU+=(',install,vsds,standby,predeploy' 'Pre-deploy install step for standby Nuage VSDs'     'playbook'    'vsd_standby_predeploy'                        ',install,vsds')
MENU+=(',install,vsds,standby,deploy'    'Deploy install step for standby Nuage VSDs'         'playbook'    'vsd_standby_deploy'                           ',install,vsds')
MENU+=(',install,vscs'                   'Install Nuage VSCs'                                 'playbook'    'install_vscs'                                 ',install')
MENU+=(',install,vscs,predeploy'         'Pre-deploy install step for Nuage VSCs'             'playbook'    'vsc_predeploy'                                ',install,vscs')
MENU+=(',install,vscs,deploy'            'Deploy install step for Nuage VSCs'                 'playbook'    'vsc_deploy'                                   ',install,vscs')
MENU+=(',install,vscs,postdeploy'        'Post-deploy install step for Nuage VSCs'            'playbook'    'vsc_postdeploy'                               ',install,vscs')
MENU+=(',install,vstats'                 'Install Nuage VSTATs (ES)'                          'playbook'    'install_vstats'                               ',install')
MENU+=(',install,vstats,predeploy'       'Pre-deploy install step for Nuage VSTATs (ES)'      'playbook'    'vstat_predeploy'                              ',install,vstats')
MENU+=(',install,vstats,deploy'          'Deploy install step for Nuage VSTATs (ES)'          'playbook'    'vstat_deploy'                                 ',install,vstats')
MENU+=(',install,vstats,postdeploy'      'Post-deploy install step for Nuage VSTATs (ES)'     'playbook'    'vstat_postdeploy'                             ',install,vstats')
MENU+=(',install,vns'                    'Install all Nuage VNS components'                   'playbook'    'install_vns'                                  ',install')
MENU+=(',install,vns,nuagex'             'Install Nuage VNS components on NuageX'             'playbook'    'install_vns_on_nuagex'                        ',install,vns')
MENU+=(',install,vns,postdeploy'         'Post-deploy for Nuage VNS components'               'playbook'    'vsd_vns_postdeploy'                           ',install,vns')
MENU+=(',install,vnsutils'               'Install Nuage Utility Hosts (NUHs)'                 'playbook'    'install_vnsutils'                             ',install')
MENU+=(',install,vnsutils,predeploy'     'Pre-deploy install step for Nuage NUHs'             'playbook'    'vnsutil_predeploy'                            ',install,vnsutils')
MENU+=(',install,vnsutils,deploy'        'Deploy install step for Nuage NUHs'                 'playbook'    'vnsutil_deploy'                               ',install,vnsutils')
MENU+=(',install,vnsutils,postdeploy'    'Post-deploy install step for Nuage NUHs'            'playbook'    'vnsutil_postdeploy'                           ',install,vnsutils')
MENU+=(',install,nsgvs'                  'Install Nuage NSGvs'                                'playbook'    'install_nsgvs'                                ',install')
MENU+=(',install,nsgvs,predeploy'        'Pre-deploy install step for Nuage NSGvs'            'playbook'    'nsgv_predeploy'                               ',install,nsgvs')
MENU+=(',install,nsgvs,postdeploy'       'Post-deploy install step for Nuage NSGvs'           'playbook'    'nsgv_postdeploy'                              ',install,nsgvs')
MENU+=(',install,nuhs'                   'Install Nuage Utility Hosts (NUHs)'                 'playbook'    'install_nuhs'                                 ',install')
MENU+=(',install,nuhs,predeploy'         'Pre-deploy install step for Nuage NUHs'             'playbook'    'nuh_predeploy'                                ',install,nuhs')
MENU+=(',install,nuhs,deploy'            'Deploy install step for Nuage NUHs'                 'playbook'    'nuh_deploy'                                   ',install,nuhs')
MENU+=(',install,nuhs,postdeploy'        'Post-deploy install step for Nuage NUHs'            'playbook'    'nuh_postdeploy'                               ',install,nuhs')
MENU+=(',install,vcs'                    'Install all Nuage VCS components'                   'playbook'    'install_vcs'                                  ',install')
MENU+=(',install,vrss'                   'Install Nuage VRSs'                                 'playbook'    'install_vrss'                                 ',install')
MENU+=(',install,vrss,predeploy'         'Pre-deploy install step for Nuage VRSs'             'playbook'    'vrs_predeploy'                                ',install,vrss')
MENU+=(',install,vrss,deploy'            'Deploy install step for Nuage VRSs'                 'playbook'    'vrs_deploy'                                   ',install,vrss')
MENU+=(',install,vrss,postdeploy'        'Post-deploy install step for Nuage VRSs'            'playbook'    'vrs_postdeploy'                               ',install,vrss')
MENU+=(',install,vcins'                  'Install vCenter Integration Nodes (VCINs)'          'playbook'    'install_vcins'                                ',install')
MENU+=(',install,vcins,predeploy'        'Pre-deploy install step for VCINs'                  'playbook'    'vcin_predeploy'                               ',install,vcins')
MENU+=(',install,vcins,deploy'           'Deploy install step for VCINs'                      'playbook'    'vcin_deploy'                                  ',install,vcins')
MENU+=(',install,vcins,postdeploy'       'Post-deploy install step for VCINs'                 'playbook'    'vcin_postdeploy'                              ',install,vcins')
MENU+=(',install,portal'                 'Install SDWAN portal'                               'playbook'    'install_sdwan_portal'                         ',install')
MENU+=(',install,portal,predeploy'       'Pre-deploy install step for SDWAN portal'           'playbook'    'sdwan_portal_predeploy'                       ',install,portal')
MENU+=(',install,portal,deploy'          'Deploy install step for SDWAN portal'               'playbook'    'sdwan_portal_deploy'                          ',install,portal')
MENU+=(',install,portal,postdeploy'      'Post-deploy install step for SDWAN portal'          'playbook'    'sdwan_portal_postdeploy'                      ',install,portal')
MENU+=(',install,portal,license'         'Update license for SDWAN portal'                    'playbook'    'sdwan_portal_license_update'                  ',install,portal')
MENU+=(',install,vsrs'                   'Install Virtualized Service Router (VSRs)'          'playbook'    'install_vsrs'                                 ',install')
MENU+=(',install,vsrs,predeploy'         'Pre-deploy install step for VCINs'                  'playbook'    'vsr_predeploy'                                ',install,vsrs')
MENU+=(',install,vsrs,deploy'            'Deploy install step for VCINs'                      'playbook'    'vsr_deploy'                                   ',install,vsrs')
MENU+=(',install,vsrs,postdeploy'        'Post-deploy install step for VCINs'                 'playbook'    'vsr_postdeploy'                               ',install,vsrs')
MENU+=(',install,stcv'                   'Install STCv VMs'                                   'playbook'    'install_stcvs'                                ',install')
MENU+=(',install,stcv,predeploy'         'Pre-deploy install step for STCv VMs'               'playbook'    'stcv_predeploy'                               ',install,stcv')
MENU+=(',install,stcv,postdeploy'        'Post-deploy install step for STCv VMs'              'playbook'    'stcv_postdeploy'                              ',install,stcv')
MENU+=(',install,proxys'                 'Install proxys'                                     'playbook'    'install_proxys'                               ',install')
MENU+=(',install,proxys,predeploy'       'Pre-deploy install step for proxys'                 'playbook'    'proxy_predeploy'                              ',install,proxys')
MENU+=(',install,proxys,deploy'          'Deploy install step for proxys'                     'playbook'    'proxy_deploy'                                 ',install,proxys')
MENU+=(',install,dns'                    'Install DNS servers'                                'playbook'    'install_dns'                                  ',install')
MENU+=(',install,dns,predeploy'          'Pre-deploy install step for DNS servers'            'playbook'    'dns_predeploy'                                ',install,dns')
MENU+=(',install,dns,deploy'             'Deploy install step for DNS servers'                'playbook'    'dns_deploy'                                   ',install,dns')
MENU+=(',install,dns,postdeploy'         'Post-deploy install step for DNS servers'           'playbook'    'dns_postdeploy'                               ',install,dns')

#################################################################################
#                              Upgrade COMMANDS                                 #
#################################################################################
MENU+=(',upgrade'                        'Run upgrades of Nuage components'                   'playbook'    'upgrade_everything'                           '')
MENU+=(',upgrade,everything'             'Upgrade all Nuage components'                       'playbook'    'upgrade_everything'                           ',upgrade')
MENU+=(',upgrade,beforevrs'              'Upgrade steps before VRS upgrade'                   'playbook'    'upgrade_before_vrs'                           ',upgrade')
MENU+=(',upgrade,aftervrs'               'Upgrade steps after VRS upgrade'                    'playbook'    'upgrade_after_vrs'                            ',upgrade')
MENU+=(',upgrade,vsds'                   'Upgrade Nuage VSDs - All VSD steps'                 'playbook'    'upgrade_vsds'                                 ',upgrade')
MENU+=(',upgrade,vsds,inplace'           'Upgrade Nuage VSDs - inplace upgrade'               'playbook'    'upgrade_vsds_inplace'                         ',upgrade')
MENU+=(',upgrade,vscs'                   'Upgrade Nuage VSCs - All VSC steps'                 'playbook'    'upgrade_vscs'                                 ',upgrade')
MENU+=(',upgrade,vscs,beforevrs'         'VSC upgrade steps before VRS upgrade'               'playbook'    'upgrade_vscs_before_vrs'                      ',upgrade,vscs')
MENU+=(',upgrade,vscs,aftervrs'          'VSC upgrade steps after VRS upgrade'                'playbook'    'upgrade_vscs_after_vrs'                       ',upgrade,vscs')
MENU+=(',upgrade,vstats'                 'Upgrade Nuage VSTATs (ES) - All VSTAT steps'        'playbook'    'upgrade_vstats'                               ',upgrade')
MENU+=(',upgrade,vrss'                   'Upgrade Nuage VRSs'                                 'playbook'    'vrs_upgrade'                                  ',upgrade')
MENU+=(',upgrade,preupgrade,health'      'Run health checks before stepwise upgrade'          'playbook'    'vsp_preupgrade_health'                        ',upgrade,preupgrade')
MENU+=(',upgrade,ha,vsd,dbbackup'        'Stepwise HA upgrade step - Backup VSD database'     'playbook'    'vsd_ha_upgrade_database_backup_and_decouple'  ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,shutdown23'      'Stepwise HA upgrade step - Shutdown VSD 2 & 3'      'playbook'    'vsd_ha_upgrade_shutdown_2_and_3'              ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,predeploy23'     'Stepwise HA upgrade step - Predeploy new VSD 2 & 3' 'playbook'    'vsd_ha_upgrade_predeploy_2_and_3'             ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,deploy23'        'Stepwise HA upgrade step - Deploy new VSD 2 & 3'    'playbook'    'vsd_ha_upgrade_deploy_2_and_3'                ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,shutdown1'       'Stepwise HA upgrade step - Shutdown VSD 1'          'playbook'    'vsd_ha_upgrade_shutdown_1'                    ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,predeploy1'      'Stepwise HA upgrade step - Predeploy new VSD 1'     'playbook'    'vsd_ha_upgrade_predeploy_1'                   ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,deploy1'         'Stepwise HA upgrade step - Deploy new VSD 1'        'playbook'    'vsd_ha_upgrade_deploy_1'                      ',upgrade,ha')
MENU+=(',upgrade,ha,vsd,complete'        'Stepwise HA upgrade step - Mark VSDs complete'      'playbook'    'vsd_upgrade_complete'                         ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,health'          'Stepwise HA upgrade step - Health check VSC'        'playbook'    'vsc_health'                                   ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,backup1'         'Stepwise HA upgrade step - Backup and prep VSC 1'   'playbook'    'vsc_ha_upgrade_backup_and_prep_1'             ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,deploy1'         'Stepwise HA upgrade step - Deploy new VSC 1'        'playbook'    'vsc_ha_upgrade_deploy_1'                      ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,postdeploy1'     'Stepwise HA upgrade step - Postdeploy new VSC 1'    'playbook'    'vsc_ha_upgrade_postdeploy_1'                  ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,backup2'         'Stepwise HA upgrade step - Backup and prep VSC 2'   'playbook'    'vsc_ha_upgrade_backup_and_prep_2'             ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,deploy2'         'Stepwise HA upgrade step - Deploy new VSC 2'        'playbook'    'vsc_ha_upgrade_deploy_2'                      ',upgrade,ha')
MENU+=(',upgrade,ha,vsc,postdeploy2'     'Stepwise HA upgrade step - Postdeploy new VSC 2'    'playbook'    'vsc_ha_upgrade_postdeploy_2'                  ',upgrade,ha')
MENU+=(',upgrade,ha,vstat,health'        'Stepwise HA upgrade step - Health check VSTAT'      'playbook'    'vstat_preupgrade_health'                      ',upgrade,ha')
MENU+=(',upgrade,ha,vstat,prep'          'Stepwise HA upgrade step - Prepare VSTAT'           'playbook'    'vstat_upgrade_prep'                           ',upgrade,ha')
MENU+=(',upgrade,ha,vstat,inplace'       'Stepwise HA upgrade step - Inplace upgrade VSTAT'   'playbook'    'vstat_upgrade'                                ',upgrade,ha')
MENU+=(',upgrade,ha,vstat,wrapup'        'Stepwise HA upgrade step - Wrapup VSTAT'            'playbook'    'vstat_upgrade_wrapup'                         ',upgrade,ha')
MENU+=(',upgrade,sa,vsd,dbbackup'        'Stepwise SA upgrade step - Backup VSD database'     'playbook'    'vsd_sa_upgrade_database_backup'               ',upgrade,sa')
MENU+=(',upgrade,sa,vsd,shutdown'        'Stepwise SA upgrade step - Shutdown VSD'            'playbook'    'vsd_sa_upgrade_shutdown'                      ',upgrade,sa')
MENU+=(',upgrade,sa,vsd,predeploy'       'Stepwise SA upgrade step - Predeploy new VSD'       'playbook'    'vsd_sa_upgrade_predeploy'                     ',upgrade,sa')
MENU+=(',upgrade,sa,vsd,deploy'          'Stepwise SA upgrade step - Deploy new VSD'          'playbook'    'vsd_sa_upgrade_deploy'                        ',upgrade,sa')
MENU+=(',upgrade,sa,vsd,complete'        'Stepwise SA upgrade step - Mark VSD complete'       'playbook'    'vsd_upgrade_complete'                         ',upgrade,sa')
MENU+=(',upgrade,sa,vsc,health'          'Stepwise SA upgrade step - Health check VSC'        'playbook'    'vsc_health'                                   ',upgrade,sa')
MENU+=(',upgrade,sa,vsc,backup'          'Stepwise SA upgrade step - Backup and prep VSC'     'playbook'    'vsc_sa_upgrade_backup_and_prep'               ',upgrade,sa')
MENU+=(',upgrade,sa,vsc,deploy'          'Stepwise SA upgrade step - Deploy new VSC'          'playbook'    'vsc_sa_upgrade_deploy'                        ',upgrade,sa')
MENU+=(',upgrade,sa,vsc,postdeploy'      'Stepwise SA upgrade step - Postdeploy new VSC'      'playbook'    'vsc_sa_upgrade_postdeploy'                    ',upgrade,sa')
MENU+=(',upgrade,sa,vstat,health'        'Stepwise SA upgrade step - Health check VSTAT'      'playbook'    'vstat_preupgrade_health'                      ',upgrade,sa')
MENU+=(',upgrade,sa,vstat,prep'          'Stepwise SA upgrade step - Prepare VSTAT'           'playbook'    'vstat_upgrade_prep'                           ',upgrade,sa')
MENU+=(',upgrade,sa,vstat,inplace'       'Stepwise SA upgrade step - Inplace upgrade VSTAT'   'playbook'    'vstat_upgrade'                                ',upgrade,sa')
MENU+=(',upgrade,sa,vstat,wrapup'        'Stepwise SA upgrade step - Wrapup VSTAT'            'playbook'    'vstat_upgrade_wrapup'                         ',upgrade,sa')
MENU+=(',upgrade,postdeploy'             'Final steps of stepwise upgrade'                    'playbook'    'vsp_upgrade_postdeploy'                       ',upgrade,')
MENU+=(',upgrade,postupgrade,health'     'Run health checks after stepwise upgrade'           'playbook'    'vsp_postupgrade_health'                       ',upgrade,postupgrade')
MENU+=(',upgrade,destroy,ha,vsd23'       'Destroy HA upgrade VSD 2 & 3 VMs'                   'playbook'    'vsd_ha_upgrade_destroy_2_and_3'               ',upgrade,destroy')
MENU+=(',upgrade,destroy,ha,vsd1'        'Destroy HA upgrade VSD 1 VM'                        'playbook'    'vsd_ha_upgrade_destroy_1'                     ',upgrade,destroy')
MENU+=(',upgrade,destroy,sa,vsd'         'Destroy SA upgrade VSD VM'                          'playbook'    'vsd_sa_upgrade_destroy'                       ',upgrade,destroy')
MENU+=(',upgrade,destroy,vstat'          'Destroy upgrade VSTAT VMs'                          'playbook'    'vstat_upgrade_destroy'                        ',upgrade,destroy')
MENU+=(',upgrade,cleanup'                'Cleanup after upgrade'                              'playbook'    'vsp_upgrade_cleanup'                          ',upgrade,')

#################################################################################
#                               Health COMMANDS                                 #
#################################################################################
MENU+=(',health'                        'Run health checks for Nuage components'              'playbook'    'nuage_health'                                 '')
MENU+=(',health,vsds'                   'Run heath check Nuage VSDs'                          'playbook'    'vsd_health'                                   ',health')
MENU+=(',health,vscs'                   'Run heath check Nuage VSCs'                          'playbook'    'vsc_health'                                   ',health')
MENU+=(',health,vstats'                 'Run heath check Nuage VSTATs'                        'playbook'    'vstat_health'                                 ',health')
MENU+=(',health,vrss'                   'Run heath check Nuage VRSs'                          'playbook'    'vrss_health'                                  ',health')
MENU+=(',health,vcins'                  'Run heath check vCenter Integration Nodes (VCINs)'   'playbook'    'vcin_health'                                  ',health')

#################################################################################
#                              Destroy COMMANDS                                 #
#################################################################################
MENU+=(',destroy'                       'Destroy Nuage components'                            'playbook'    'destroy_everything'                           '')
MENU+=(',destroy,everything'            'Destroys all running Nuage components'               'playbook'    'destroy_everything'                           ',destroy')
MENU+=(',destroy,vsds'                  'Destroy Nuage VSDs'                                  'playbook'    'vsd_destroy'                                  ',destroy')
MENU+=(',destroy,vscs'                  'Destroy Nuage VSCs'                                  'playbook'    'vsc_destroy'                                  ',destroy')
MENU+=(',destroy,vstats'                'Destroy Nuage VSTATs (ES)'                           'playbook'    'vstat_destroy'                                ',destroy')
MENU+=(',destroy,vnsutils'              'Destroy Nuage VNSUtils'                              'playbook'    'vnsutil_destroy'                              ',destroy')
MENU+=(',destroy,nsgvs'                 'Destroy Nuage NSGvs'                                 'playbook'    'nsgv_destroy'                                 ',destroy')
MENU+=(',destroy,nuhs'                  'Destroy Nuage Utility Hosts (NUHs)'                  'playbook'    'nuh_destroy'                                  ',destroy')
MENU+=(',destroy,vrss'                  'Destroy Nuage VRSs'                                  'playbook'    'vrs_destroy'                                  ',destroy')
MENU+=(',destroy,vcins'                 'Destroy vCenter Integration Nodes (VCINs)'           'playbook'    'vcin_destroy'                                 ',destroy')
MENU+=(',destroy,portal'                'Destroy SDWAN portal'                                'playbook'    'sdwan_portal_destroy'                         ',destroy')
MENU+=(',destroy,vsrs'                  'Destroy Virtualized Service Routers (VSRs)'          'playbook'    'vsr_destroy'                                  ',destroy')
MENU+=(',destroy,dns'                   'Destroy DNS servers'                                 'playbook'    'dns_destroy'                                  ',destroy')

#################################################################################
#                                 VSD COMMANDS                                  #
#################################################################################
MENU+=(',vsd'                           'Run workflows for VSD components'                    ''            ''                                             '')
MENU+=(',vsd,services,start'            'Starts all services on VSDs'                         'playbook'    'vsd_services_start'                           ',vsd')
MENU+=(',vsd,services,stop'             'Stops all services on VSDs'                          'playbook'    'vsd_services_stop'                            ',vsd')
MENU+=(',vsd,services,restart'          'Restarts all services on VSDs'                       'playbook'    'vsd_services_restart'                         ',vsd')
MENU+=(',vsd,license'                   'Adds a license to VSD'                               'playbook'    'vsd_license'                                  ',vsd')
MENU+=(',vsd,branding'                  'Brands custom UI for VSDs'                           'playbook'    'brand_vsd'                                    ',vsd')
MENU+=(',vsd,failover'                  'Initiates a failover to standby VSDs'                'playbook'    'vsd_cluster_failover'                         ',vsd')
MENU+=(',vsd,dbbackup'                  'Backup the VSD database'                             'playbook'    'vsd_dbbackup'                                 ',vsd')
MENU+=(',vsd,decouple'                  'Decouple the VSD cluster'                            'playbook'    'vsd_decouple'                                 ',vsd')
MENU+=(',vsd,certificates,renew'        'Renew certificates on VSDs'                          'playbook'    'renew_vsd_certificates'                       ',vsd')
MENU+=(',vsd,disk,test'                 'Test disk peformance on VSDs'                        'playbook'    'vsd_disk_performance_test'                    ',vsd')
#################################################################################
#                                 VSC COMMANDS                                  #
#################################################################################
MENU+=(',vsc'                           'Run workflows for VSC components'                    ''            ''                                             '')
MENU+=(',vsc,backup'                    'Backup the VSC image'                                'playbook'    'vsc_backup'                                   ',vsc')
MENU+=(',vsc,harden'                    'Harden the VSC for security'                         'playbook'    'vsc_harden'                                   ',vsc')

#################################################################################
#                                VSTAT COMMANDS                                 #
#################################################################################
MENU+=(',vstat'                         'Run workflows for VSTAT components'                  ''            ''                                             '')
MENU+=(',vstat,setup,vssui'             'Setup VSTAT VSS UI'                                  'playbook'    'setup_vstat_vss_ui'                           ',vstat')
MENU+=(',vstat,failover'                'Initiates a failover to secondary VSTATs'            'playbook'    'vstat_failover'                               ',vstat')
MENU+=(',vstat,failback'                'Initiates a failback to primary VSTATs'              'playbook'    'vstat_failback'                               ',vstat')

#################################################################################
#                                Tools COMMANDS                                 #
#################################################################################
MENU+=(',tools'                         'Run MetroAE Tools'                                   'tools'       ''                                             '')
MENU+=(',tools,build'                   'Perform a manual build of inventory'                 'playbook'    'build'                                        ',tools')
MENU+=(',tools,build,reset'             'Clear the inventory'                                 'playbook'    'reset_build'                                  ',tools')
MENU+=(',tools,collect,debugs'          'Collect debug information for troubleshooting'       'tools'       'get_debug'                                    ',tools')
MENU+=(',tools,convert,csv'             'Convert spreadsheet (CSV) to deployment'             'tools'       'convert_csv_to_deployment'                    ',tools')
MENU+=(',tools,copy,qcow'               'Copy qcow2 images to target server'                  'playbook'    'copy_qcow2_files'                             ',tools')
MENU+=(',tools,encrypt,credentials'     'Encrypt credentials.yml in your deployment'          'tools'       'encrypt-credentials'                          ',tools')
MENU+=(',tools,generate,example'        'Generate a deployment file from its schema'          'tools'       'generate-example-from-schema'                 ',tools')
MENU+=(',tools,unzip,images'            'Unzip Nuage images'                                  'tools'       'unzip-files'                                  ',tools')

#################################################################################
#                                Setup                                          #
#################################################################################
MENU+=(',setup'                         'Setup MetroAE on host'                               'setup'       ''                                             '')

#################################################################################
#                                Wizard                                         #
#################################################################################
MENU+=(',wizard'                        'Run MetroAE Wizard'                                  'wizard'      ''                                             '')
